BANK_REGISTRY = {
    1: {
        "name": "Banco Union S.A.",
        "engine": "postgresql",
        "database": "banco_union",
        "api_port": 8001,
        "algorithm": "CAESAR",
    },
    2: {
        "name": "Banco Mercantil Santa Cruz S.A.",
        "engine": "postgresql",
        "database": "banco_mercantil_santa_cruz",
        "api_port": 8002,
        "algorithm": "ATBASH",
    },
    3: {
        "name": "Banco Nacional de Bolivia S.A. (BNB)",
        "engine": "postgresql",
        "database": "banco_nacional_bolivia",
        "api_port": 8003,
        "algorithm": "VIGENERE",
    },
    4: {
        "name": "Banco de Credito de Bolivia S.A. (BCP)",
        "engine": "mysql",
        "database": "banco_credito_bolivia",
        "api_port": 8004,
        "algorithm": "PLAYFAIR",
    },
    5: {
        "name": "Banco BISA S.A.",
        "engine": "mysql",
        "database": "banco_bisa",
        "api_port": 8005,
        "algorithm": "HILL",
    },
    6: {
        "name": "Banco Ganadero S.A.",
        "engine": "mysql",
        "database": "banco_ganadero",
        "api_port": 8006,
        "algorithm": "DES",
    },
    7: {
        "name": "Banco Economico S.A.",
        "engine": "sqlserver",
        "database": "banco_economico",
        "api_port": 8007,
        "algorithm": "3DES",
    },
    8: {
        "name": "Banco Prodem S.A.",
        "engine": "sqlserver",
        "database": "banco_prodem",
        "api_port": 8008,
        "algorithm": "BLOWFISH",
    },
    9: {
        "name": "Banco Solidario S.A.",
        "engine": "sqlserver",
        "database": "banco_solidario",
        "api_port": 8009,
        "algorithm": "TWOFISH",
    },
    10: {
        "name": "Banco Fortaleza S.A.",
        "engine": "mongodb",
        "database": "banco_fortaleza",
        "api_port": 8010,
        "algorithm": "AES",
    },
    11: {
        "name": "Banco FIE S.A.",
        "engine": "mongodb",
        "database": "banco_fie",
        "api_port": 8011,
        "algorithm": "RSA",
    },
    12: {
        "name": "Banco PYME de la Comunidad S.A.",
        "engine": "cassandra",
        "database": "banco_pyme_comunidad",
        "api_port": 8012,
        "algorithm": "ELGAMAL",
    },
    13: {
        "name": "Banco de Desarrollo Productivo S.A.M.",
        "engine": "cassandra",
        "database": "banco_desarrollo_productivo",
        "api_port": 8013,
        "algorithm": "ECC",
    },
    14: {
        "name": "Banco de la Nacion Argentina",
        "engine": "cassandra",
        "database": "banco_nacion_argentina",
        "api_port": 8014,
        "algorithm": "CHACHA20",
    },
}